### ISSUE TITLE
feature request for checkDeps.R

### ISSUE THREAD

**Issue by orichters** [pik-piam/lucode2#127]
- as discussed here with @0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q: https://github.com/remindmodel/remind/pull/1028
- add a parameter `whattodo` (or similar):
  - "warn": basically what it does now, but without the call signature from somewhere inside Map() which is likely to confuse people
  - "stop": throw an error; what @mikapfl is getting at
  - "pass": invisibly return the state of all packages (for use in other functions)
  - "update": update all without asking
  - "ask": for each package (or once for all), run:
```
     message("Do you want to update your renv? y/n")
     if (tolower(gms::getLine()) %in% c("y", "yes")) { renv::install('package'); renv::snapshot(prompt = FALSE) }
```
 
 you may even install with `renv::install('package@0.0.16')` just the required package version. I don't know if the snapshot part is necessary, you know better.

**Comment by pfuehrlich-pik** [comment]
The `renv::snapshot` is necessary so the renv.lock is updated. The renv.lock is used to ensure the same package environment in newly started runs. So without renv::snapshot you'd not actually use the newly installed package in your runs.

**Comment by mikapfl** [comment]
I think this is done.
