### ISSUE TITLE
running buildLibrary() introduces superfluous blanks in man files

### ISSUE THREAD

**Issue by orichters** [pik-piam/lucode2#164]
see attached, here for `gms` package. Maybe a thing for @pfuehrlich-pik?

![image](https://user-images.githubusercontent.com/90761609/219368201-05688f1d-efae-416b-a725-1bb8af70a94e.png)

See https://github.com/pik-piam/gms/pull/54/files

**Comment by pfuehrlich-pik** [comment]
Is this breaking something?

**Comment by pfuehrlich-pik** [comment]
I'd say this is fine for auto-generated files. Also, I don't really know where to start fixing this, so it probably would take longer and thus does not seem to be worth the effort.
