### ISSUE TITLE
getGitHubRepo() may return list of remotes, bedazzeling other functions

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/lucode2#19]
https://github.com/pik-piam/lucode2/blob/b7865d5f3370f39bcb187a411f1847f425e0fc87/R/package2readme.R#L24-L37

- `usethis::git_remotes()` returns all remotes in alphabetic order
- `getGitHubRepo()` returns the vector of all remotes,
- which leads to `fillGithubActions()` and `fillCodecov()` to pass vectors to `fillTemplate()`,
- which causes warnings by `gsub()` (`In gsub(paste0("[:", what, ":]"), fill[[what]], x, fixed = TRUE) :  argument 'replacement' has length > 1 and only the first element will be used`), and
- writes random (alphabetically first remote) URLs into the `README.md`, potentially pointing badges to a different fork, e.g.
	https://raw.githubusercontent.com/pik-piam/quitte/fc279b4a1345098b9be25ff2d4d8f35c91390922/README.md
	```markdown
	[![CRAN status](https://www.r-pkg.org/badges/version/quitte)](https://cran.r-project.org/package=quitte)   [![R build status](https://pik.github.com/giannou/quitte/workflows/check/badge.svg)](https://pik.github.com/giannou/quitte/actions) [![codecov](https://codecov.io/gh/giannou/quitte/branch/master/graph/badge.svg)](https://codecov.io/gh/giannou/quitte)
	```

Consider looking for the `origin` branch (most likely to exist), or else use only the first remote explicitly:
```
return(.harmonize(ifelse('origin' %in% names(out), out[['origin']], origin[[1]])))
```

**Comment by tscheypidi** [comment]
Thanks, fixed in acc4eea
