### ISSUE TITLE
function lucode2::buildlibrary adds file .buildlibrary to .gitignore?

### ISSUE THREAD

**Issue by giannou** [pik-piam/lucode2#4]
Although I didn't find any indication of that in the function, this is the observed behavior. Why does this happen?

**Comment by tscheypidi** [comment]
If you say observed behavior, can you show me an example? 
It is added to .Rbuildignore, but not to .gitignore

**Comment by giannou** [comment]
@0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q did you add it by hand in this commit? https://github.com/pik-piam/mrremind/commit/70e996ae75553f5cdaf1e65d1c88724d360a4347

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Yeah, I did.  Figured if it's ignored by R, it can be ignored by git.
Sorry.

**Comment by tscheypidi** [comment]
so it is clarified then
