### ISSUE TITLE
tell people how to switch off linter warning

### ISSUE THREAD

**Issue by orichters** [pik-piam/lucode2#59]
Hey, if you have set `allowLinterWarnings: no` in `R/.buildlibrary`, then linter warnings break the completion of `buildLibrary()`. 

It would be fantastic to tell the reader in the stop message in [L61 of `check.R`](https://github.com/pik-piam/lucode2/blob/master/R/check.R#L61) that the option to set `allowLinterWarnings: yes` exists.

**Comment by pfuehrlich-pik** [comment]
allowLinterWarnings should only be changed after discussing with all people working on a package, so I would not suggest everyone to just change that setting when they have linter warnings. For all existing packages the default setting is `allowLinterWarnings: yes`, only if a new .buildLibrary is created it is `allowLinterWarnings: no`. With the additional check before creating a new .buildLibrary it is unlikely that a new .buildLibrary is created unintentionally, so I believe we can leave this as is.

**Comment by orichters** [comment]
fine!
