### ISSUE TITLE
buildlibrary not very flexible in creating README

### ISSUE THREAD

**Issue by MariannaR** [pik-piam/lucode2#6]
When building a library with lucode2::buildlibrary(), the README file is overwritten following some standards. The only field that in my understanding can be customized is the `Description` field in the DESCRIPTION file, but this field does not allow for e.g. inserting code chunks, going to a new line, including paragraphs... wouldn't it be better to have a "fully customizable" README section?

**Comment by Loisel** [comment]
+1

**Comment by tscheypidi** [comment]
lucode2 version >= 0.6 supports allows now to deactive the automatic README.md creation via setting the argument `AutocreateReadme: no` in the `.buildlibrary` configuration file.

However, the recommended method still would be to add your package description to the `Description` section in the `DESCRIPTION` file and code chunks to a vignette coming with the package, even if this does not provide the full level of flexibility in styling your description which the markdown format provides.

**Comment by MariannaR** [comment]
Many thanks for implementing this and for your suggestions!
