### ISSUE TITLE
Request by RR: add the option to disable tests in buildlibrary()

### ISSUE THREAD

**Issue by giannou** [pik-piam/lucode2#7]
more info here: https://github.com/pik-piam/remind2/pull/2#issuecomment-783242008

**Comment by giannou** [comment]
I opened the issue so some discussion can take place

**Comment by tscheypidi** [comment]
I agree with @Renato-Rodrigues that long tests are considerably hampering the code development and should be avoided. But `buildLibrary` is the wrong place to deal with this problem as it just runs the tests as defined in the model. (it just runs `devtools::check()`).
I would strongly encourage to think again about @Renato-Rodrigues suggestion to speed up the existing test. From my perspective good tests should not take longer than a few seconds.
