### ISSUE TITLE
`package2readme()` writes wrong version number in README.md

### ISSUE THREAD

**Issue by chroetz** [pik-piam/lucode2#79]
When developing an R package, `buildLibrary()` updates the version number of the package in different places. [Here](https://github.com/pik-piam/lucode2/blob/95d892fc0bad59603b68bece912f28a87b7c2eda/R/buildLibrary.R#L230) the `DESCRIPTION` is written with the new version number. [Here](https://github.com/pik-piam/lucode2/blob/95d892fc0bad59603b68bece912f28a87b7c2eda/R/buildLibrary.R#L234) it calls `package2readme()` to recreate the `README.md` with the new version number. In `package2readme()` the template [README_template.md](https://github.com/pik-piam/lucode2/blob/master/inst/extdata/README_template.md) is filled with infos from the `DESCRIPTION` file. At the beginning of the template, `[:version:]` is replaced by the correct new version number. At the end of the template, `[:cite:]` is replaced by the result of [`fillCite()`](https://github.com/pik-piam/lucode2/blob/d0bc63d94948bf8bd4bbf44939082ef5abbbb84b/R/package2readme.R#L113), which seems to create the citation text from the installed version of the R package and thus uses an old wrong version number.

[Here](https://github.com/pik-piam/remind2/pull/202/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) is an example of the result of `buildLibrary()` on a README.md.

**Comment by tscheypidi** [comment]
Hi Christof, 
this one is a nasty problem we are aware of, but which we have left as it is so far, as we do not know a good way to tell the `citation` function in `fillCite` to use the local source copy as reference rather than using the installed version as reference. If you have an idea how to fix it without potentially introducing other issues, we would be glad to hear about it.

I will close the issue for now as long as now good solution is on the table and as long as the problem does not occur frequently.

**Comment by chroetz** [comment]
Hi Jan, thanks for the quick reply.

After some experimenting, I think `citation(auto = packageDescription(folderName, pathToWhereFolderIs))` should work. `folderName` is the name of the folder of the local source copy (not necessarily equal to the package name) and `pathToWhereFolderIs` is a (potentially relative) path to the folder containing the folder of the local source copy.

I can try to implement this and create a pull request if you like.

**Comment by tscheypidi** [comment]
yeah, I saw that approach. The reason why I thought this might be an unstable solution is that it is not guaranteed that the folder name is also the name of the package. Hence, one needs to do some file path magic to first figure out what the name of the package folder is. I am just not sure whether such a implementation will be less error prone compared to the current one, but you can give it a try if you like.

**Comment by chroetz** [comment]
Ok, I have an implementation in #80. I needed to add a modified version of the `citation_doi()` function in the `CITATION` file as a new lucode2 function `citationDoi()` to get the `doi` fields right. (I don't fully understand the CITATION file, so I am not entirely sure my implementation makes sense.)
