### ISSUE TITLE
.pre-commit-config related commit causes an issue

### ISSUE THREAD

**Issue by johanneskoch94** [pik-piam/lucode2#85]
pik-piam/mrdrivers@15fe2e7a666829b553e55c4333bc9043dc6ae596
This automatic commit does some unecessary stuff (I think) but definitely causes an issue by removing the last line of tests/testthat/_snaps/snaphsots.md. Any ideas?

**Comment by mikapfl** [comment]
Probably something like:
```
exclude: '^tests/testthat/_snaps/.*$'
```
at the start of the `.pre-commit-config.yaml` would do the trick. I guess everything in `_snaps` is machine-generated, but for regression tests it is anyway checked into git?

**Comment by mikapfl** [comment]
But I'd like to understand the problem first, what is breaking and how can I reproduce the error?

**Comment by johanneskoch94** [comment]
> Probably something like:
> 
> ```
> exclude: '^tests/testthat/_snaps/.*$'
> ```
> 
> at the start of the `.pre-commit-config.yaml` would do the trick. I guess everything in `_snaps` is machine-generated, but for regression tests it is anyway checked into git?

Exactly. 
I don't know how to create an easy reproducible example.. but I guess you could create any snapshot test, accept the snapshot, then manually edit the snapshot.md file and delete the last empty line. That is what produces the error on my side at least ;)
This is the error:
![image](https://user-images.githubusercontent.com/43963181/163389777-5c396669-99b7-4f5f-86ff-b11add73de3e.png)

**Comment by mikapfl** [comment]
Hi,

so, I'm trying to recreate the problem. As a first step, I try to run mrdriver's tests using testthat, but that fails unrelatedly:
```R
r$> devtools::test()
ℹ Loading mrdrivers
Loading required package: madrat
Loading required package: magclass
ℹ Testing mrdrivers
✔ | F W S  OK | Context
✔ |     1   0 | calcOutput_sets                                                                                                             
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error: invalid version specification ‘6402’
In addition: Warning messages:
1: In dir.create(value, recursive = TRUE) :
  cannot create dir '/home/johannes', reason 'Permission denied'
2: In normalizePath(value, winslash = "/") :
  path[1]="/home/johannes/madrat_folder": No such file or directory
3: In dir.create(value, recursive = TRUE) :
  cannot create dir '/home/johannes', reason 'Permission denied'
4: In normalizePath(value, winslash = "/") :
  path[1]="/home/johannes/madrat_folder/cache/test_mrdrivers": No such file or directory
```
Somehow, paths from your computer @johanneskoch94 ended up in the tests of mrdriver?

**Comment by johanneskoch94** [comment]
Hi, thanks for looking into this! 
So the test setup in mrdrivers is really still in a bit of an experimental stage. The key point is, that I've tried to set it up in such a way, that the tests only run, if the user manually sets the path to the madrat_mainfolder in tests/testthat/setup-madrat_config.R - the reason being that they take quite some time, and require madrat sources, mappings, etc.... Thanks to your message above (you're the first to have tried to test mrdrivers on their machine apart from me I think), I realize that this was done badly. Even though I don't know what the error message is saying, the warnings below are due to my misunderstanding of what `madrat::setConfig` does. I've pushed a new version of mrdrivers, where the skipping of the tests should be more transparent. I hope the error message will disappear as well. Maybe you could try to test with the new version? Without you doing anything, all tests should be skipped. If you then want to run the tests, you'll have to modify tests/testthat/setup-madrat_config.R.
